first commit automatic movement camera
mgonnav/CG-3-Mosqueteros pull request #37
Opened 2021-07-03 07:05 UTC by BasicAlgorithm

Decide if Y automatic movement go or not.
This function is on AutomaticCamera() on main.cpp (latest lines)

2021-07-04 00:45 UTC, rodp63 requested changes
Just a little fix, everything seems good

2021-07-04 00:45 UTC, rodp63 commented on cubito/Setting.hpp
> +  std::cout << "\t|     CAMERA CONTROLS (if automatic if off)    |\n";
Change the `if` for `is`.

2021-07-05 00:26 UTC, mgonnav requested changes

2021-07-05 00:26 UTC, mgonnav commented on cubito/World.hpp
> +void World::Draw(
El primer parámetro, `model`, nunca se usa. No debería pasarse.

2021-07-05 00:26 UTC, mgonnav commented on cubito/World.hpp
> +	glm::mat4& look_at) {
`look_at` y `projection` no se modifican, por lo que deberían ser `const glm::mat4&`. De hecho, no me compilar si no son `const`.

2021-07-05 00:26 UTC, mgonnav commented on cubito/Camera.hpp
>    glm::mat4 GetViewMatrix();
Las funciones `GetViewMatrix()` y `GetViewAirPlane()` deberían ser `const`, pues no modifican nada dentro de la cámara.

2021-07-06 20:02 UTC, rodp63 approved these changes
Carry

2021-07-06 22:40 UTC, mgonnav approved these changes

2021-07-06 22:41 UTC, merged